version: '3.6'
services:
  url-shortener:
    build:
      context: ../../..
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=urlshortener
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JAVA_ENABLE_DEBUG=true
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=urlshortener
  redis:
    image: redis
    ports:
      - "6379:6379"